#!/usr/bin/env python3
"""Generate Markdown documentation from a Python module's docstrings."""

import importlib
import inspect
import sys
from textwrap import dedent, indent


class MakeDoc:
    """Markdown documentation generator for Python modules."""

    def main(self) -> None:
        """Parse arguments and generate documentation for the specified module."""

        if len(sys.argv) != 2:
            print(f"Usage: {sys.argv[0]} module", file=sys.stderr)
            sys.exit(2)

        modname = sys.argv[1]
        mod = importlib.import_module(modname)

        print(f"## {modname}")
        print()
        print(self.dedent_doc(mod.__doc__))
        print()

        for symbol in mod.__all__:
            obj = getattr(mod, symbol)
            if inspect.isclass(obj):
                print(f"### class {symbol}")
                print()
                print(self.dedent_doc(obj.__doc__))
                print()
            elif inspect.isfunction(obj):
                sig = inspect.signature(obj)
                print(f"### function {symbol}")
                print()
                print(f"```python\n{symbol}{sig}\n```")
                print()
                print(indent(self.dedent_doc(obj.__doc__), " " * 4))
                print()
            elif inspect.ismethod(obj):
                print(f"### method {symbol}")
                print()
                print(self.dedent_doc(obj.__doc__))
                print()
            elif inspect.ismodule(obj):
                pass  # print(f"Skipping MODULE {symbol!r}")
            else:
                print("<unhandled>")

    def dedent_doc(self, doc: str | None) -> str:
        """Dedent and return the docstring."""

        if not doc:
            return ""

        try:
            i = doc.index("\n")
        except ValueError:
            return doc  # Single-line docstring.

        # Multi-line docstring.
        s = doc[:i]  # Copy the 1st line.
        # Copy newlines until start of 2nd (non-blank) line.
        while doc[i] == "\n":
            s += "\n"
            i += 1

        # Dedent lines 2 through the remainder.
        s += dedent(doc[i:])
        return s


if __name__ == "__main__":
    MakeDoc().main()
